### ISSUE TITLE
How about using a picker instead of a number pad?

### ISSUE THREAD

**Issue by KaitoMuraoka** [uhooi/Loki#49]
## Outline
Suggestions for `TextField` input on the registration screen (`SakatsuInputView`)

## Suggest
I suggest changing the keyboard type from `numberPad` to Picker.

## Advantages and disadvantages from existing
Picker is more intuitive than `numberPad` for entering numbers

----------------------------------------

## 概要
登録画面(`SakatsuInputView`)にて、`TextField`の入力に関する提案

## 提案内容
キーボードタイプを`numberPad`からPickerに変更した方が良いと考える

## 既存からのメリット・デメリット
`numberPad`よりもPickerの方が、直感的に数字を入力することができる

**Comment by uhooi** [comment]
Thanks for the suggestion!
But personally, I'd rather type with `numberPad` ...

---

提案ありがとー！
でも個人的には `.numberPad` で入力したい、、

**Comment by uhooi** [comment]
#56 limits the amount of time a file can be saved.
But since there is no alert and it is not friendly, I will try to implement some way to inform users in the future.

---

とりあえず #56 で保存できる時間を制限しました。
ただアラートも何も出ず不親切なので、何かしらユーザーに伝える手段を今後実装しようと思います。
